### ISSUE TITLE
Compatibility with net6

### ISSUE THREAD

**Issue by kzimny** [keyone2693/ImageResizer.AspNetCore#12]
I'm getting an error running Azure DevOps CI pipeline:

##[error]The nuget command failed with exit code(1) and error(NU1202: Package ImageResizer.AspNetCore 1.9.0 is not compatible with net60 (.NETFramework,Version=v6.0). Package ImageResizer.AspNetCore 1.9.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)

There is no error when compiling project on local machine. You declared the package for [DotNetCore ](https://github.com/keyone2693/ImageResizer.AspNetCore#its-for-dotnetcore-only) only. Any chance to migrate?

**Comment by keyone2693** [comment]
can u try now with the new version

**Comment by keyone2693** [comment]
> I'm getting an error running Azure DevOps CI pipeline:
> 
> ##[error]The nuget command failed with exit code(1) and error(NU1202: Package ImageResizer.AspNetCore 1.9.0 is not compatible with net60 (.NETFramework,Version=v6.0). Package ImageResizer.AspNetCore 1.9.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
> 
> There is no error when compiling project on local machine. You declared the package for [DotNetCore ](https://github.com/keyone2693/ImageResizer.AspNetCore#its-for-dotnetcore-only) only. Any chance to migrate?

Can you please try now, with the new version

**Comment by keyone2693** [comment]
> I'm getting an error running Azure DevOps CI pipeline:
> 
> ##[error]The nuget command failed with exit code(1) and error(NU1202: Package ImageResizer.AspNetCore 1.9.0 is not compatible with net60 (.NETFramework,Version=v6.0). Package ImageResizer.AspNetCore 1.9.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
> 
> There is no error when compiling project on local machine. You declared the package for [DotNetCore ](https://github.com/keyone2693/ImageResizer.AspNetCore#its-for-dotnetcore-only) only. Any chance to migrate?

Can you please try now, with the new version

**Comment by kzimny** [comment]
Unfortunately the new version doesn't work because IFileProvider introduced in previous PR cannot be resolved.

![image](https://user-images.githubusercontent.com/12007674/190598846-09d896d4-538b-4fa3-b29b-b3e9706da0b9.png)

Any idea how to fix it?

**Comment by keyone2693** [comment]
> Unfortunately the new version doesn't work because IFileProvider introduced in previous PR cannot be resolved.
> 
> ![image](https://user-images.githubusercontent.com/12007674/190598846-09d896d4-538b-4fa3-b29b-b3e9706da0b9.png)
> 
> Any idea how to fix it?

look at the test example. 
something like this:

            services.AddSingleton<IFileProvider>(_ => new PhysicalFileProvider(_env.WebRootPath ?? _env.ContentRootPath));
