### ISSUE TITLE
relative path to image only works with wwwroot folder

### ISSUE THREAD

**Issue by nexthor** [keyone2693/ImageResizer.AspNetCore#5]
when i try to set the src image to some folder like '~/images/my-image.jpg?w=100&h=100&mode=crop' should to have the same effect as you try with '~/wwwroot/images/my-image.jpg?w=100&h=100&mode=crop', but the first one doesn't do anything until you add the wwwroot prefix.

otherwise this library is awesome!

**Comment by keyone2693** [comment]
so I think you should add this

`app.UseStaticFiles(new StaticFileOptions()
            {
                RequestPath = new PathString("/wwwroot")
            });`

instead of this on

` app.UseStaticFiles();`

**Comment by kzimny** [comment]
It works fine on my side on IIS and Kestrel server. If images are not saved in wwwroot folder, you need to add the StaticFileOptions as follow:
```
            app.UseStaticFiles(new StaticFileOptions
            {
                FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "MyImageFolder")),
                RequestPath = "/MyImageFolder"
            });
```
