### ISSUE TITLE
ImageResizer is hooking into the pipeline but simply not working

### ISSUE THREAD

**Issue by maslade** [keyone2693/ImageResizer.AspNetCore#8]
I'm not a .NET developer so I'm in new territory and not familiar with how to diagnose the problem. I've followed the instructions in the README and compared my project to the sample project and I don't seem to be doing anything different other than not targeting net5.0. When I test this with a sample image in wwwroot, I can get the original image no matter what parameters I tack into the URL. The console output shows the middleware triggering, and it indicates the right height/width that is in the URL.

I'm probably doing something dumb but could use a pointer.

***.csproj***
```csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ImageResizer.AspNetCore" Version="1.9.0" />
  </ItemGroup>


</Project>
```

***.startup***
```cs
        // ...boilerplate...

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddImageResizer();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();
            app.UseRouting();
            app.UseAuthorization();
            app.UseImageResizer();
            app.UseStaticFiles();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
```

***Console output***
```log
    info: ImageResizer.AspNetCore.ImageResizerMiddleware[0]
          Resizing /1680.jpg with params w: 200, h: 0, autorotate: False, quality: 100, format: jpg, mode: max, wmtext: 0, wmimage: 0
    info: ImageResizer.AspNetCore.ImageResizerMiddleware[0]
          Resizing /1680.jpg with params w: 0, h: 100, autorotate: False, quality: 100, format: jpg, mode: max, wmtext: 0, wmimage: 0
    info: ImageResizer.AspNetCore.ImageResizerMiddleware[0]
          Resizing /1680.jpg with params w: 100, h: 100, autorotate: False, quality: 100, format: jpg, mode: max, wmtext: 0, wmimage: 0
```

***Browser request***
4.5MB is the original file, and based on the 200 I'm ruling out a caching issue.

![image](https://user-images.githubusercontent.com/930769/103152652-1d590700-4758-11eb-9e3e-d56a13e53909.png)

**Comment by kzimny** [comment]
The configuration seems to be fine. Did you put the ImageResizer.json in your root directory? https://github.com/keyone2693/ImageResizer.AspNetCore/tree/master/TestExample/wwwroot

**Comment by maslade** [comment]
I hadn't - but I just added it (copied straight from the example) and getting the same results.  In case I've omitted anything important, here's a minimum reproducing repo:

https://github.com/maslade/image-resizer-troubles

**Comment by keyone2693** [comment]
Hi sorry I did not see this issue
I believe the best option right now is 

https://github.com/imazen/imageflow-dotnet-server

If one-day imageflow get completely unfree
I will expand this package!
Until that day please use imageflow

**Comment by dewebeloper** [comment]
Hi @maslade 
I have exactly same issue, did you solve it somehow?

**Comment by maslade** [comment]
I'm afraid not!

**Comment by dewebeloper** [comment]
Hi @maslade 
I found this https://www.paddo.org/asp-net-core-image-resizing-middleware/.
Mako some small changes and make it work for me.
Maybe can be usefull for you too.
